# Generated by Django 4.1 on 2023-09-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('image', models.ImageField(default=None, upload_to='current_receipt')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
